<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Exception;

class PatentType extends Model
{
    //
    protected $appends = ['logo_url'];

    public function getLogoUrlAttribute()
    {
        if (!empty($this->attributes['logo']) && Storage::disk('public')->exists($this->attributes['logo'])) {
            return Storage::disk('public')->url($this->attributes['logo']);
        }
        return '';
    }

    public function delete()
    {
        if ($this->id < 4 || $this->patent->first()) {
            throw new Exception('此类型不能删除');
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function patent()
    {
        return $this->hasMany(Patent::class);
    }
}
